### PR TITLE
docs: rename CLI reference

### PR DESCRIPTION
**Pull request by deepeshaburse**
This PR renames the CLI Reference section to ORAS Commands.

### CODE REVIEW

**Comment by deepeshaburse** [comment]
> There is that other PR where I'm renaming CLI_Reference to cli_reference. I'd like to get rid of any upper case directory names. Can you maybe just make this `commands` since oras_commands is kind of repetitive. You'd also need to do a scan of links and attempt to fix them 

Yes, sure. 👍🏼

**Comment by deepeshaburse** [comment]
> Why is this a draft?

@TerryHowe I need to go over some commands with you and @FeynmanZhou before I mark it ready for review.

**Comment by TerryHowe** [comment]
I don't think we need to hold this for that conversation. Let's get this directory renaming rolling

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by asmitbm — APPROVED** [review]
LGTM 🚀

**Pull request merged**
