### PR TITLE
Explain how to install oras snap

### PR DESCRIPTION
**Pull request by SamirPS**
This PR add the new way of installing oras

### CODE REVIEW

**Comment by SamirPS** [comment]
Here is the PR for creating the snap: https://github.com/oras-project/oras/pull/965

After that you will need to follow this tutorial : https://ubuntu.com/tutorials/create-your-first-snap#7-push-to-the-store to push the snap into the snap store ( you have github action to do it also) and finally merge the https://github.com/oras-project/oras-www/pull/188

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by FeynmanZhou** [comment]
We will merge this PR after https://github.com/oras-project/oras/pull/965 is merged

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Pull request merged**
