### PR TITLE
feat: initial commit for docusaurus migration

### PR DESCRIPTION
**Pull request by asmitbm**
This the initial commit for new website migration.

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@asmitbm Please sign your commit to pass DCO check.

**Review by SteveLasker — APPROVED** [review]
LGTM for a dev branch. 
Before we move to main, we, unfortunately, need to address the golang redirect concerns.
Assumed plan:
- Include redirects in the www code, no worse than we have today
- Have a plan to migrate off oras.land dependencies to avoid accidental doc changes to break dependencies.

**Comment by FeynmanZhou** [comment]
@shizhMSFT Could you help enable the Netlify preview feature for the `dev` branch?

**Comment by FeynmanZhou** [comment]
> LGTM for a dev branch. Before we move to main, we, unfortunately, need to address the golang redirect concerns. Assumed plan:
> 
> * Include redirects in the www code, no worse than we have today
> * Have a plan to migrate off oras.land dependencies to avoid accidental doc changes to break dependencies.

Thank you @SteveLasker 's suggestions. Could you clarify the oras.land dependencies that we need to consider during this migration?

**Comment by shizhMSFT** [comment]
Closing and re-opening to re-trigger checks

**Comment by shizhMSFT** [comment]
@asmitbm It seems that I'm not able to re-trigger the checks and build although I've set up the deploy preview for the `dev` branch. Could you make some new commits to trigger the checks and build?

**Comment by asmitbm** [comment]
> @asmitbm It seems that I'm not able to re-trigger the checks and build although I've set up the deploy preview for the `dev` branch. Could you make some new commits to trigger the checks and build?

Yupp sure, doing that right away!

**Comment by asmitbm** [comment]
Hey @shizhMSFT, the preview link seems to be broken: https://deploy-preview-140--oras-project.netlify.app/

**Comment by shizhMSFT** [comment]
@asmitbm The preview link is correct as it says
image

If the website is not deployed or non-existing, it will show
image

Here's the deployment log for reference:
```log
10:34:06 AM: build-image version: 442a909cc19725b67a71cc230a935e063dadf683 (focal)
10:34:06 AM: buildbot version: 716793686322a0f551ced71ae75eb84b472ba215
10:34:06 AM: Building without cache
10:34:06 AM: Starting to prepare the repo for build
10:34:06 AM: No cached dependencies found. Cloning fresh repo
10:34:06 AM: git clone --filter=blob:none https://github.com/oras-project/oras-www
10:34:06 AM: Preparing Git Reference pull/140/head
10:34:07 AM: Parsing package.json dependencies
10:34:08 AM: Starting to install dependencies
10:34:08 AM: Python version set to 3.8
10:34:08 AM: Attempting Ruby version 2.7.1, read from environment
10:34:09 AM: Required ruby-2.7.1 is not installed - installing.
10:34:09 AM: Searching for binary rubies, this might take some time.
10:34:09 AM: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.7.1.tar.bz2
10:34:09 AM: Checking requirements for ubuntu.
10:34:09 AM: Requirements installation successful.
10:34:10 AM: ruby-2.7.1 - #configure
10:34:10 AM: ruby-2.7.1 - #download
10:34:10 AM: ruby-2.7.1 - #validate archive
10:34:13 AM: ruby-2.7.1 - #extract
10:34:15 AM: ruby-2.7.1 - #validate binary
10:34:15 AM: ruby-2.7.1 - #setup
10:34:15 AM: ruby-2.7.1 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.7.1@global
10:34:15 AM: ruby-2.7.1 - #importing gemset /opt/buildhome/.rvm/gemsets/global.gems........................................
10:34:15 AM: ruby-2.7.1 - #generating global wrappers........
10:34:15 AM: ruby-2.7.1 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.7.1
10:34:16 AM: ruby-2.7.1 - #importing gemsetfile /opt/buildhome/.rvm/gemsets/default.gems evaluated to empty gem list
10:34:16 AM: ruby-2.7.1 - #generating default wrappers........
10:34:16 AM: Using /opt/buildhome/.rvm/gems/ruby-2.7.1
10:34:16 AM: Using Ruby version 2.7.1
10:34:17 AM: Started restoring cached go cache
10:34:17 AM: Finished restoring cached go cache
10:34:17 AM: Installing Go version 1.19.5 (requested 1.19.5)
10:34:21 AM: go version go1.19.5 linux/amd64
10:34:22 AM: Using PHP version 8.0
10:34:23 AM: Downloading and installing node v12.18.0...
10:34:23 AM: Downloading https://nodejs.org/dist/v12.18.0/node-v12.18.0-linux-x64.tar.xz...
10:34:23 AM: Computing checksum with sha256sum
10:34:23 AM: Checksums matched!
10:34:24 AM: Now using node v12.18.0 (npm v6.14.4)
10:34:24 AM: Started restoring cached build plugins
10:34:24 AM: Finished restoring cached build plugins
10:34:24 AM: Started restoring cached corepack dependencies
10:34:24 AM: Finished restoring cached corepack dependencies
10:34:24 AM: No npm workspaces detected
10:34:24 AM: Started restoring cached node modules
10:34:24 AM: Finished restoring cached node modules
10:34:25 AM: Installing npm packages using npm version 6.14.4
10:34:36 AM: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
10:34:36 AM: > core-js@3.29.0 postinstall /opt/build/repo/node_modules/core-js
10:34:36 AM: > node -e "try{require('./postinstall')}catch(e){}"
10:34:36 AM: > core-js-pure@3.29.0 postinstall /opt/build/repo/node_modules/core-js-pure
10:34:36 AM: > node -e "try{require('./postinstall')}catch(e){}"
10:34:37 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
10:34:37 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:34:37 AM: added 1095 packages from 744 contributors and audited 1100 packages in 12.103s
10:34:37 AM: 200 packages are looking for funding
10:34:37 AM:   run `npm fund` for details
10:34:37 AM: found 11 vulnerabilities (5 moderate, 6 high)
10:34:37 AM:   run `npm audit fix` to fix them, or `npm audit` for details
10:34:37 AM: npm packages installed
10:34:37 AM: Install dependencies script success
10:34:37 AM: No build steps found, continuing to publishing
10:34:38 AM: Starting to deploy site from '/'
10:34:38 AM: Calculating files to upload
10:34:38 AM: 0 new files to upload
10:34:38 AM: 0 new functions to upload
10:34:38 AM: Section completed: deploying
10:34:38 AM: Starting post processing
10:34:38 AM: Section completed: building
10:34:38 AM: Post processing - HTML
10:34:38 AM: Post processing - header rules
10:34:38 AM: Post processing - redirect rules
10:34:38 AM: Post processing done
10:34:38 AM: Section completed: postprocessing
10:34:39 AM: Uploading Cache of size 7.9MB
10:34:39 AM: Section completed: cleanup
10:34:39 AM: Finished processing build request in 33.539s
10:34:39 AM: Site is live ✨
```

You might want to update your code for a fix.

**Comment by shizhMSFT** [comment]
I've also checked what netlify has deployed.

For `main` branch:
```console
$ ls -l
total 80
-rwxrwxrwx 1 shizh shizh 30124 Apr 13 10:49 404.html
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 assets
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 blog
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 cli
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 cli_reference
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 client_libraries
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 community
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 contributing
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 custom
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 implementors
-rwxrwxrwx 1 shizh shizh 36404 Apr 13 10:49 index.html
-rwxrwxrwx 1 shizh shizh   261 Apr 13 10:49 netlify.toml
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 oras
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 oras-credentials-go
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 oras-go
drwxrwxrwx 1 shizh shizh  4096 Apr 13 10:49 search
-rwxrwxrwx 1 shizh shizh  7595 Apr 13 10:49 sitemap.xml
-rwxrwxrwx 1 shizh shizh   625 Apr 13 10:49 sitemap.xml.gz
```

For this PR:
```console
$ ls -l
total 420
-rwxrwxrwx 1 shizh shizh     89 Apr 13 10:49 babel.config.js
drwxrwxrwx 1 shizh shizh   4096 Apr 13 10:49 blog
-rwxrwxrwx 1 shizh shizh    153 Apr 13 10:49 code_of_conduct.md
-rwxrwxrwx 1 shizh shizh     84 Apr 13 10:49 codeowners
drwxrwxrwx 1 shizh shizh   4096 Apr 13 10:49 docs
drwxrwxrwx 1 shizh shizh   4096 Apr 13 10:49 docs-old
-rwxrwxrwx 1 shizh shizh   5039 Apr 13 10:49 docusaurus.config.js
-rwxrwxrwx 1 shizh shizh  11338 Apr 13 10:49 license
-rwxrwxrwx 1 shizh shizh    240 Apr 13 10:49 owners.md
-rwxrwxrwx 1 shizh shizh 396375 Apr 13 10:49 package-lock.json
-rwxrwxrwx 1 shizh shizh   1055 Apr 13 10:49 package.json
-rwxrwxrwx 1 shizh shizh   1116 Apr 13 10:49 readme.md
-rwxrwxrwx 1 shizh shizh    781 Apr 13 10:49 sidebars.js
drwxrwxrwx 1 shizh shizh   4096 Apr 13 10:49 src
drwxrwxrwx 1 shizh shizh   4096 Apr 13 10:49 static
```

As you can observe, the `index.html` is missing.

**Comment by asmitbm** [comment]
Hey @shizhMSFT those logs doesn't seem to be of a docusaurus site. That seems to be of the old Mkdocs site. So, for checking whether this code had a problem, I deployed this site on my repository's `dev` branch: https://github.com/asmitbm/oras-www/tree/dev

And the Netlify's site seems to be working on `dev` branch: https://effervescent-gumdrop-38adc5.netlify.app/

Here are my logs:

```
9:21:38 AM: build-image version: 442a909cc19725b67a71cc230a935e063dadf683 (focal)
9:21:38 AM: buildbot version: 716793686322a0f551ced71ae75eb84b472ba215
9:21:38 AM: Fetching cached dependencies
9:21:38 AM: Failed to fetch cache, continuing with build
9:21:38 AM: Starting to prepare the repo for build
9:21:38 AM: No cached dependencies found. Cloning fresh repo
9:21:38 AM: git clone --filter=blob:none https://github.com/asmitbm/oras-www
9:21:38 AM: Preparing Git Reference refs/heads/dev
9:21:40 AM: Parsing package.json dependencies
9:21:41 AM: Starting to install dependencies
9:21:41 AM: Python version set to 3.8
9:21:41 AM: Attempting Ruby version 2.7.2, read from environment
9:21:42 AM: Using Ruby version 2.7.2
9:21:42 AM: Started restoring cached go cache
9:21:42 AM: Finished restoring cached go cache
9:21:42 AM: Installing Go version 1.19.5 (requested 1.19.5)
9:21:47 AM: go version go1.19.5 linux/amd64
9:21:47 AM: Using PHP version 8.0
9:21:48 AM: v16.20.0 is already installed.
9:21:49 AM: Now using node v16.20.0 (npm v8.19.4)
9:21:49 AM: Enabling Node.js Corepack
9:21:49 AM: Started restoring cached build plugins
9:21:49 AM: Finished restoring cached build plugins
9:21:49 AM: Started restoring cached corepack dependencies
9:21:49 AM: Finished restoring cached corepack dependencies
9:21:49 AM: No npm workspaces detected
9:21:49 AM: Started restoring cached node modules
9:21:49 AM: Finished restoring cached node modules
9:21:49 AM: Installing npm packages using npm version 8.19.4
9:21:52 AM: npm WARN deprecated trim@0.0.1: Use String.prototype.trim() instead
9:21:52 AM: npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
9:22:03 AM: added 1095 packages, and audited 1096 packages in 13s
9:22:03 AM: 200 packages are looking for funding
9:22:03 AM:   run `npm fund` for details
9:22:03 AM: 22 vulnerabilities (9 moderate, 13 high)
9:22:03 AM: To address issues that do not require attention, run:
9:22:03 AM:   npm audit fix
9:22:03 AM: Some issues need review, and may require choosing
9:22:03 AM: a different dependency.
9:22:03 AM: Run `npm audit` for details.
9:22:03 AM: npm packages installed
9:22:03 AM: Install dependencies script success
9:22:03 AM: Starting build script
9:22:04 AM: Detected 1 framework(s)
9:22:04 AM: "docusaurus-v2" at version "2.3.1"
9:22:04 AM: Section completed: initializing
9:22:05 AM: ​
9:22:05 AM:   Netlify Build                                                 
9:22:05 AM: ────────────────────────────────────────────────────────────────
9:22:05 AM: ​
9:22:05 AM: ❯ Version
9:22:05 AM:   @netlify/build 29.9.1
9:22:05 AM: ​
9:22:05 AM: ❯ Flags
9:22:05 AM:   baseRelDir: true
9:22:05 AM:   buildId: 64377c413387b240fd335cf8
9:22:05 AM:   deployId: 64377c413387b240fd335cfa
9:22:05 AM: ​
9:22:05 AM: ❯ Current directory
9:22:05 AM:   /opt/build/repo
9:22:05 AM: ​
9:22:05 AM: ❯ Config file
9:22:05 AM:   No config file was defined: using default values.
9:22:05 AM: ​
9:22:05 AM: ❯ Context
9:22:05 AM:   production
9:22:05 AM: ​
9:22:05 AM:   1. Build command from Netlify app                             
9:22:05 AM: ────────────────────────────────────────────────────────────────
9:22:05 AM: ​
9:22:05 AM: $ npm run build
9:22:05 AM: > build
9:22:05 AM: > docusaurus build
9:22:06 AM: [INFO] [en] Creating an optimized production build...
9:22:07 AM: [info] [webpackbar] Compiling Client
9:22:07 AM: [info] [webpackbar] Compiling Server
9:22:25 AM: [success] [webpackbar] Client: Compiled successfully in 18.32s
9:22:28 AM: [success] [webpackbar] Server: Compiled successfully in 20.73s
9:22:33 AM: [WARNING] Docusaurus found broken links!
9:22:33 AM: 
9:22:33 AM: Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
9:22:34 AM: Starting post processing
9:22:34 AM: Post processing - HTML
9:22:36 AM: Post processing - header rules
9:22:36 AM: Post processing - redirect rules
9:22:36 AM: Post processing done
9:22:37 AM: Section completed: postprocessing
9:22:37 AM: Site is live ✨
9:22:33 AM: [SUCCESS] Generated static files in "build".
9:22:33 AM: [INFO] Use `npm run serve` command to test your build locally.
9:22:33 AM: ​
9:22:33 AM: (build.command completed in 28.3s)
9:22:33 AM: ​
9:22:33 AM:   2. Deploy site                                                
9:22:33 AM: ────────────────────────────────────────────────────────────────
9:22:33 AM: ​
9:22:33 AM: Starting to deploy site from 'build'
9:22:34 AM: Calculating files to upload
9:22:34 AM: 56 new files to upload
9:22:34 AM: 0 new functions to upload
9:22:34 AM: Section completed: deploying
9:22:34 AM: Site deploy was successfully initiated
9:22:34 AM: ​
9:22:34 AM: (Deploy site completed in 496ms)
9:22:34 AM: ​
9:22:34 AM:   Netlify Build Complete                                        
9:22:34 AM: ────────────────────────────────────────────────────────────────
9:22:34 AM: ​
9:22:34 AM: (Netlify Build completed in 28.9s)
9:22:34 AM: Caching artifacts
9:22:34 AM: Started saving node modules
9:22:34 AM: Finished saving node modules
9:22:34 AM: Started saving build plugins
9:22:34 AM: Finished saving build plugins
9:22:34 AM: Started saving corepack cache
9:22:34 AM: Finished saving corepack cache
9:22:34 AM: Started saving pip cache
9:22:34 AM: Finished saving pip cache
9:22:34 AM: Started saving emacs cask dependencies
9:22:34 AM: Finished saving emacs cask dependencies
9:22:34 AM: Started saving maven dependencies
9:22:34 AM: Finished saving maven dependencies
9:22:34 AM: Started saving boot dependencies
9:22:34 AM: Finished saving boot dependencies
9:22:34 AM: Started saving rust rustup cache
9:22:34 AM: Finished saving rust rustup cache
9:22:34 AM: Started saving go dependencies
9:22:34 AM: Finished saving go dependencies
9:22:35 AM: Build script success
9:22:35 AM: Section completed: building
9:22:36 AM: Uploading Cache of size 115.8MB
9:22:37 AM: Section completed: cleanup
9:22:37 AM: Finished processing build request in 59.147s
```

Here are my settings:
Screenshot (528)

**Comment by asmitbm** [comment]
Ohh I understood the problem (kinda). Netlify is set to deploy from `dev` branch. So, the [`dev` branch in this repository](https://github.com/oras-project/oras-www/tree/dev) has old Mkdocs files and config. As a result, it is deploying the Mkdocs and not Docusarus files.

Here's the ref from my logs:
> 9:21:38 AM: git clone --filter=blob:none https://github.com/asmitbm/oras-www
9:21:38 AM: Preparing Git Reference refs/heads/dev

Possible soultion would be to merge this PR in `dev`, so old Mkdocs files will be replaced with new Docusaurus files. After that if we deploy the `dev` branch again, it will deploy the Docusaurus files. Any new PRs to `dev` branch will have Docusaurus configuration.

**Comment by FeynmanZhou** [comment]
@asmitbm I agree that we can first merge this PR into dev. Then check if the Netlify preview settings work as our expectations.

**Comment by shizhMSFT** [comment]
Here's the build settings for `oras.land`.
image

I should not modify it as it will impact the `main` branch.

**Comment by shizhMSFT** [comment]
You should use [file-based configuration](https://docs.netlify.com/configure-builds/file-based-configuration/) instead.

**Comment by asmitbm** [comment]
> You should use [file-based configuration](https://docs.netlify.com/configure-builds/file-based-configuration/) instead.

What if we add multiple branches for deploy previews like this:
 Screenshot (530)

**Comment by shizhMSFT** [comment]
> > You should use [file-based configuration](https://docs.netlify.com/configure-builds/file-based-configuration/) instead.
> 
> What if we add multiple branches for deploy previews like this: Screenshot (530)

It's already done yesterday.
image

Basically, the file-based configuration allows you to have different build settings for different branches.

**Comment by shizhMSFT** [comment]
Note that the production branch must be the `main` branch. Otherwise, production users will be impacted without notifce.

**Comment by asmitbm** [comment]
Okay, will commit the necessary changes then.

**Comment by asmitbm** [comment]
@shizhMSFT @FeynmanZhou The issue seems to be fixed now! 😄

**Pull request merged**
