### PR TITLE
Resolved #152 Added dependabot.yml

### LINKED ISSUE #152: Use dependabot to track dependency update
Some dependencies in [package.json](https://github.com/oras-project/oras-www/blob/main/package.json) is outdated but never notified or updated. We can introduce dependabot to improve that.

### PR DESCRIPTION
**Pull request by RickDeb2004**
Closes: #152
This pull request Resolves Issue #152 
Added dependabot.yml

### CODE REVIEW

**Comment by TerryHowe** [comment]
Closes: https://github.com/oras-project/oras-www/issues/152

**Comment by TerryHowe** [comment]
> Closes: #152

If you put the comment in this form, it will close the issue automatically

**Comment by RickDeb2004** [comment]
> > Closes: #152
> 
> If you put the comment in this form, it will close the issue automatically

Done ,what you said

**Comment by shizhMSFT** [comment]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
