### PR TITLE
moving python docs to own repository

### PR DESCRIPTION
**Pull request by vsoch**
I was originally going to add a manual trigger to update docs, but this workflow has been broken for 6 months and I was not notified (I do not get notifications for actions here). This PR will remove the previously working automation that updated the Python docs, and have them served directly from the original (and official) source. This is important because the workflow here is not reliable to provide consistently building and updated docs to the oras python user community, which is my number one priority.

The netlify build needs to have it's base image updated, which is also a problem in #68. Hopefully one of the maintainers has permission to do that (I do not).

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
When CNCF helps us to fix the Netlify build issue, we can merge this PR. I raised a service ticket to CNCF and now it's still WIP. https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1527

**Comment by vsoch** [comment]
Thank you @FeynmanZhou !

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
The Netlify problem has been fixed. I agree that we can maintain the ORAS-py documentation at https://oras-project.github.io/oras-py now. 

Sorry for bringing the bad experience.

**Pull request merged**
