### PR TITLE
Move Zot to quick start

### PR DESCRIPTION
**Pull request by sajayantony**

### CODE REVIEW

**Comment by sajayantony** [comment]
This also updates the side bar as shown below - 

image

**Review by FeynmanZhou — DISMISSED** [review]
LGTM. Thanks @sajayantony .

**Comment by sajayantony** [comment]
Needed to fix Phase number incorrect ordering and better image.

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Pull request merged**
