### PR TITLE
cleanup codebase and use Link component

### PR DESCRIPTION
**Pull request by asmitbm**
* Cleaned up unused files from Docusaurus setup. 

* Fixed improper routing by using Docusaurus' `<Link>` component. More info here: https://docusaurus.io/docs/docusaurus-core#link. This will reduce pageload.

* Also, fixed the `description` of oras and oras go pages which were earlier irrelevant.

Closes: #224

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by sajayantony** [comment]
I'm curious why the quickstart doesn't show up on these previews. 

image

image

**Comment by asmitbm** [comment]
> I'm curious why the quickstart doesn't show up on these previews.
> 
> image image

Oh, that's because #226 was merged before this PR which is #225. I will rebase the branch.

**Comment by asmitbm** [comment]
> I'm curious why the quickstart doesn't show up on these previews.
> 
> image image

Should be fixed now: https://deploy-preview-225--oras-project.netlify.app/docs/quickstart

**Review by TerryHowe — APPROVED** [review]

**Review by sajayantony — APPROVED** [review]

**Pull request merged**
