### PR TITLE
doc: update installation guide to v1.1.0

### PR DESCRIPTION
**Pull request by qweeah**
This PR updates installation guide for ORAS CLI v1.1.0. Changes for specific package managers are depending on merging of below PRs:
- winget: https://github.com/microsoft/winget-pkgs/pull/118903
- homebrew: https://github.com/Homebrew/homebrew-core/pull/141435

### CODE REVIEW

**Comment by qweeah** [comment]
The lint job fails, can anyone help rerun it?

**Comment by FeynmanZhou** [comment]
> The lint job fails, can anyone help rerun it?

It is caused by https://github.com/actions/checkout/issues/1448. It seems this issue could be fixed after updating to actions/checkout@v4.

**Comment by FeynmanZhou** [comment]
I opened a PR to fix this issue.  https://github.com/oras-project/oras-www/pull/258

**Review by asmitbm — COMMENTED** [review]
@qweeah @FeynmanZhou Since we are changing version numbers on the installation guide, I think we also need to change the version number in docusaurus.config file.

https://github.com/oras-project/oras-www/blob/56ad143b78bc5be5f2f223802613ae438b7e8c67/docusaurus.config.js#L60

**Comment by qweeah** [comment]
> @qweeah @FeynmanZhou Since we are changing version numbers on the installation guide, I think we also need to change the version number in docusaurus.config file.
> 
> https://github.com/oras-project/oras-www/blob/56ad143b78bc5be5f2f223802613ae438b7e8c67/docusaurus.config.js#L60

@asmitbm Can you help explain how is this label used?

**Review by shizhMSFT — COMMENTED** [review]
What if we don’t specify the version for winget? What version will it install?

**Comment by qweeah** [comment]
> What if we don’t specify the version for winget? What version will it install?

1.1.0

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Comment by FeynmanZhou** [comment]
> @qweeah @FeynmanZhou Since we are changing version numbers on the installation guide, I think we also need to change the version number in docusaurus.config file.
> 
> https://github.com/oras-project/oras-www/blob/56ad143b78bc5be5f2f223802613ae438b7e8c67/docusaurus.config.js#L60

@asmitbm Good catch. Let's update it in a follow-up PR.

**Comment by shizhMSFT** [comment]
@qweeah If winget always install the latest version of `oras`, then I don't think we need to specify the version just like homebrew. /cc @FeynmanZhou

**Pull request merged**
