### PR TITLE
[Add adopter]: Score

### PR DESCRIPTION
**Pull request by mathieu-benoit**
https://github.com/oras-project/oras-www/issues/409

### CODE REVIEW

**Comment by TerryHowe** [comment]
Screenshot 2024-10-31 at 6 27 17 AM

**Review by TerryHowe — DISMISSED** [review]
/lgtm

Although in theory, you could have the note as your image, but "score" wouldn't be the right font.

**Comment by mathieu-benoit** [comment]
@TerryHowe, I think it's way much better now, right?
https://deploy-preview-410--oras-project.netlify.app/adopters

image

**Comment by TerryHowe** [comment]
Looks like you need to `git commit --amend --signoff; git push --force` for DCO

**Comment by mathieu-benoit** [comment]
@TerryHowe, I just fixed the DCO, thanks!

**Comment by mathieu-benoit** [comment]
Out of curiosity, anything missing on my end here?

**Comment by TerryHowe** [comment]
> Out of curiosity, anything missing on my end here?

No I was just waiting on another review.

**Review by FeynmanZhou — APPROVED** [review]
LGTM. Thanks @mathieu-benoit for adding Score as a new adopter

**Pull request merged**
