### PR TITLE
fix: irregular behavior when clicked on sidebar Oras go link 

### LINKED ISSUE #98: Irregular behavior when clicked on sidebar Oras go link
*Describe the bug* 
When clicked on Oras go button on Sidebar it redirects to the GitHub Repository 

Expected Behaviour:
The link should generate a text that is a link to the repo so that the repo opens in a new tab .

https://user-images.githubusercontent.com/76839614/216815244-7c63a24e-1cd6-4ef7-b615-52fa98239e61.mp4

### PR DESCRIPTION
**Pull request by Amishakumari544**
Signed-off-by: Amishakumari544 <amishakumari544@gmail.com>
This PR fixes #98 

Check the result [here](https://orasredirect.netlify.app/) after approving will update the official links

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@Amishakumari544 Thanks. Can we hide the ORAS and ORAS-go links in the sidebar?

**Review by FeynmanZhou — COMMENTED** [review]
@Amishakumari544 Thanks. Can we hide the ORAS and ORAS-go links in the sidebar?

**Review by TerryHowe — CHANGES_REQUESTED** [review]
This only covers 2 of I think 3 cases and hopefully we can resolve this with Hugo

**Comment by TerryHowe** [comment]
This probably isn't needed anymore

**Pull request closed without merging**
