### PR TITLE
Recommend sembr for docs

### PR DESCRIPTION
**Pull request by sajayantony**
Preview link - https://deploy-preview-249--oras-project.netlify.app/docs/community/contributing_guide#development-environment-setup

### CODE REVIEW

**Comment by sajayantony** [comment]
@TerryHowe - Do you think we should avoid line breaks at 80 and just do one line a sentence. I couldn't understand if symbr recommends the line breaks or not and the only guidance was for line breaks at a sentence.

**Comment by TerryHowe** [comment]
I don't need line breaks at 80, but I could go either way on that.

**Comment by sajayantony** [comment]
Agreed. I also find holding the 80 char limit hard :) 
How about we recommend breaking lines between 80-120 but ensure that sentences are on new lines?

**Comment by TerryHowe** [comment]
Does this need to be a draft still?

**Comment by sajayantony** [comment]
Update review status @TerryHowe

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by sajayantony** [comment]
@shizhMSFT @FeynmanZhou any concerns?

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
