### PR TITLE
doc: add new implementors

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

### CODE REVIEW

**Comment by developer-guy** [comment]
kindly ping @FeynmanZhou @shizhMSFT

**Comment by developer-guy** [comment]
kindly ping @FeynmanZhou @shizhMSFT

**Review by FeynmanZhou — APPROVED** [review]
@developer-guy Sorry for the late response. @shizhMSFT and I just get back from the Chinese New Year holiday and continue to work on the project today. 

This PR looks good to me. I am curious how did you identify the implementors? Looking at the dependencies in their `go.mod`?

cc @oras-project/oras-www-maintainers

**Comment by developer-guy** [comment]
> @developer-guy Sorry for the late response. @shizhMSFT and I just get back from the Chinese New Year holiday and continue to work on the project today. 
> 
> 
> 
> This PR looks good to me. I am curious how did you identify the implementors? Looking at the dependencies in their `go.mod`?

Why didn't you invite me to the party ? 🙈 yeah exactly these are the projects I know thar they are already using Oras SDKs

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
