### PR TITLE
docs: Added reference to oras-dotnet API docs

### PR DESCRIPTION
**Pull request by sammychinedu2ky**
docs: Added reference to oras-dotnet API docs

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
Would you mind creating a dedicated intro page for oras-dotnot? See oras-go lib page as an example: https://oras.land/docs/client_libraries/go

**Comment by TerryHowe** [comment]
Anything on this? I don't recall an intro page in another PR

**Comment by FeynmanZhou** [comment]
> Anything on this? I don't recall an intro page in another PR

@sammychinedu2ky Could you update it in this PR? Thanks

**Comment by sammychinedu2ky** [comment]
> > Anything on this? I don't recall an intro page in another PR
> 
> @sammychinedu2ky Could you update it in this PR? Thanks

Update what?

**Comment by TerryHowe** [comment]
Update this: _Would you mind creating a dedicated intro page for oras-dotnot? See oras-go lib page as an example: https://oras.land/docs/client_libraries/go_

**Comment by sammychinedu2ky** [comment]
@TerryHowe I waiting for a persistent store to be available. Currently what is supported is a Memory target and copying from one Registry to Another

**Review by sajayantony — APPROVED** [review]

**Pull request merged**
