### PR TITLE
fix: update nav structure to exclude redirect links on navbar

### PR DESCRIPTION
**Pull request by asmitbm**
I read Mkdocs documentation and found this page on [custom navigation](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation), where we can structure our navbar using `nav` key. It's a bit of manual work, but easiest approach until the documentation is migrated. There's no additional plugin used.

Fixes: #98 

## Screenshot:
Screenshot (449)

Cc: @FeynmanZhou @TerryHowe @shizhMSFT

### CODE REVIEW

**Review by TerryHowe — COMMENTED** [review]
This definitely works, the downside is the nav has to be manually maintained.

**Comment by Asmit2952** [comment]
> This definitely works, the downside is the nav has to be manually maintained.

Yupp, but I think the migration would happen within 3 months (LFX term). So, I think we can maintain this for that much time.

**Review by TerryHowe — CHANGES_REQUESTED** [review]
This makes sense to me, but maybe hold for Hugo?

**Comment by asmitbm** [comment]
Closing this PR, since we have moved to new website framework #147

**Pull request closed without merging**
