### PR TITLE
doc: fix outdated information

### PR DESCRIPTION
**Pull request by FeynmanZhou**

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
Can you just remove the year from these copyrights?

**Comment by TerryHowe** [comment]
would have been nice to rebase instead of merge from main for the commit history. Not sure if this project squashes, but even then, this commit history can cause merge issues

**Comment by vsoch** [comment]
At least in jekyll there is a variable  to reference the year - possibly find the equivalent of that here and don't render from the yaml?

**Comment by TerryHowe** [comment]
This resolves this issue for now https://github.com/oras-project/oras-www/pull/125

**Pull request closed without merging**
