### PR TITLE
doc: update installation guide for 1.0.0-rc.2

### PR DESCRIPTION
**Pull request by qweeah**
Confirmed on linux/amd64 and windows/amd64

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
LGTM

Seems  like if these instructions set `RELEASE=1.0.0-rc.2` and used that, the number of changes would be smaller

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Comment by FeynmanZhou** [comment]
> LGTM
> 
> Seems like if these instructions set `RELEASE=1.0.0-rc.2` and used that, the number of changes would be smaller

Agree, we might need to set the RELEASE tag as an environment variable in this guide. @qweeah @TerryHowe @oras-project/oras-cli

**Comment by qweeah** [comment]
> I can raise another PR to update it.

@FeynmanZhou Thanks. Things will get little complicated when the command need to cover both bash and zsh(mac default). I have updated workable bash, zsh and windows commands in my own fork. You may refer to  https://github.com/qweeah/oras-www/blob/1.0.0-rc.2/docs/CLI/index.md to save some time.

**Pull request merged**
