### PR TITLE
Remove next documents in favor of two releases at a time.

### PR DESCRIPTION
**Pull request by TerryHowe**
Maintaining 3 copies of the documents will be very difficult making sure fixes happen for each version. This PR reduces the number to 2. We can use the latest release at the basis for the next new release.

### CODE REVIEW

**Review by asmitbm — COMMENTED** [review]
I'm not sure if Docusaurus recommends removing the main docs from the `/docs` folder. Instead, we can rename the `Next` docs to match the current version we're working on and keep the last version.

**Comment by TerryHowe** [comment]
It seems to work fine from the preview.

**Comment by asmitbm** [comment]
> It seems to work fine from the preview.

Yes, it does, but when we need to create new versioned docs, we'll need the source docs located in the /docs folder.

Ref: https://docusaurus.io/docs/versioning#tagging-a-new-version

**Comment by TerryHowe** [comment]
That is really just a process.

I'm not opposed to having docs be latest i.e 1.2 right now, but I'd like to have no more than 2 copies of the docs normally.

**Comment by qweeah** [comment]
LGTM although IANAM

IMHO, it's better to use a dedicated branch to track the doc of next version.

**Review by FeynmanZhou — APPROVED** [review]
LGTM. It avoids ambiguity to just keep the versioned doc folder per our discussion in the meeting.

**Pull request merged**
