### PR TITLE
testing workflow to update oras-py docs

### PR DESCRIPTION
**Pull request by vsoch**
This is testing the workflow to update the oras-py docs. I currently have a PR trigger to see if it works as expected. When that works to open a PR here, we can remove it and then I'll test the repository dispatch event. When that works, I'll add to oras-py and we can test the whole thing from merge into main to docs update PR here. When that works we can remove the PR and have it directly push.

This should not be merged, etc. until the PR is confirmed to look good, and we remove the PR trigger!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
@jdolitsky this is my suggested fix for the docs, along with the repository dispatch workflow that will (eventually) be used to automatically update here when oras-py is changed! If we are already using pip, it doesn't make a lot of sense to add an additional dependency (poetry) to accomplish the same thing. I tested the previous version of poetry and updating pip (neither worked) and looking at the bug, I traced it to here https://github.com/python-poetry/poetry/blob/ec89ac45ba4ca16ea860652540673c423d430457/src/poetry/utils/env.py#L1671 and it could be some change with respect to the environment in netlify that we can't control - I don't know enough about netlify to say yay or nay! But I think removing poetry and doing a simple install from requirements.txt is a reasonable approach.

**Review by sajayantony — APPROVED** [review]

**Comment by vsoch** [comment]
Why is this not ready for merge?

**Comment by vsoch** [comment]
We need the dispatch workflow here in the main branch to finish up the work to automate the docs added here for oras-py.  I also fixed the building bug.

**Comment by vsoch** [comment]
This event:
```yaml
on:
  repository_dispatch:
    types: [oras-py-update]
```
is only triggered via a http request (authenticated) to the repo here, which won't happen on merge or any other event.

**Comment by sajayantony** [comment]
Apologize. I was not recommending that it not be merged. I was looking at the description 
> This should not be merged, etc. until the PR is confirmed to look good, and we remove the PR trigger!

So if you feel its good enough, more than happy to see it merged :)

**Comment by vsoch** [comment]
oh right!  Sorry that's my bad - that really just says it shouldn't be merged until it's reviewed, which is probably obvious and I don't need to say it :laughing: 

After this is merged I can test the dispatch event locally, and when that works I'll have it added to oras-py as a new workflow and then we can test that full thing. And then (if desired) we can change from PR to push.

**Pull request merged**
