### PR TITLE
fix: update the README with the latest installation guide

### LINKED ISSUE #91: Improve the build experience
I tried to follow the [development](https://github.com/oras-project/oras-www#development) guide to build the project on my local machine. 
However, I ended up installing several dependencies manually, and those installation steps are not listed in the README.

I think we should improve the build experience by improving the package management and the documentation.

### PR DESCRIPTION
**Pull request by Amishakumari544**
Signed-off-by: Amishakumari544 <amishakumari544@gmail.com>

This PR fixes #91

### CODE REVIEW

**Comment by TerryHowe** [comment]
LGTM

**Review by Wwwsylvia — APPROVED** [review]
LGTM. Thanks for fixing this!😀

**Review by FeynmanZhou — APPROVED** [review]
LGTM. Thanks for your contribution! @Amishakumari544

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
