### PR TITLE
Adding redirect plugin to handle oras and oras-go

### LINKED ISSUE #22: https://oras.land/oras-go returns html as plaintext instead of renderign it
I suppose that the way https://oras.land/oras-go looks is not what was intended :)

### PR DESCRIPTION
**Pull request by vsoch**
I am not familiar with mkdocs and I haven't used poetry much (so let me know if I did something wrong in adding a dependency) but it seems like using a redirect plugin for the oras and oras-go pages that are intended to do that is a straight forward way to fix the bug! I tested this locally and it seemed to work.

This will fix #22 

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
ping @jdolitsky !

**Comment by jdolitsky** [comment]
@vsoch - thanks for looking into this, but I think this breaks Go imports:

```go
package main

import (
	"fmt"

	"deploy-preview-23--oras-project.netlify.app/oras-go"
)

func main() {
	fmt.Println(oras.X)
}
```
```
$ go mod tidy
go: finding module for package deploy-preview-23--oras-project.netlify.app/oras-go
...
	deploy-preview-23--oras-project.netlify.app/oras-go: cannot find module providing package deploy-preview-23--oras-project.netlify.app/oras-go: unrecognized import path "deploy-preview-23--oras-project.netlify.app/oras-go": parse https://deploy-preview-23--oras-project.netlify.app/oras-go?go-get=1: no go-import meta tags ()
```

**Comment by vsoch** [comment]
Huh i wasn't even aware that was a thing - what about just preserving both files?

**Comment by vsoch** [comment]
Let me know if you want me to try that, otherwise I'll just close.

**Comment by vsoch** [comment]
Is this interaction with Go documented anywhere? I don't know how to test or debug without this knowledge.

**Comment by jdolitsky** [comment]
To be honest, I copied this from somewhere. But looks like some info here: https://pkg.go.dev/cmd/go#hdr-Remote_import_paths

**Comment by vsoch** [comment]
I mean could you show me docs to reproduce the test you did above? It's not just writing that file to the oras-www directory because there is no go.mod there. You can safely assume I don't know anything about this setup (because I don't) and I need to understand how to reproduce that so I can test stuffs.

**Review by jdolitsky — APPROVED** [review]

**Pull request merged**
