### PR TITLE
chore: move next version into versioned_docs folder

### PR DESCRIPTION
**Pull request by qweeah**
## What is done
All docs about next version of ORAS, as well as the community docs are moved from `./docs` to `./versioned_docs/version-next`

### Folder structure before the change:
```console
> tree
.
├── docs                       <--- docs of next version
├── versioned_docs
│   ├── version-1.1            <--- docs of version v1.1.0
│   └── version-1.2            <--- docs of version v1.2.0
...
```

### Folder structure after the change:
```console
> tree
.
├── versioned_docs
│   ├── static
│   ├── version-1.1            <--- docs of version v1.1.0
│   ├── version-1.2            <--- docs of version v1.2.0
│   └── version-next           <--- docs of next version
...
```

## Why it's needed
After merging of #316, when I start to work on #324, I am totally lost on which file should I modify so that only documents regarding v1.2.0 can be changed. To align the folder structure and avoid such confusion, it's better to place all the documents into `versioned-docs` with dedicated folder for each version.

### CODE REVIEW

**Comment by qweeah** [comment]
Seems that how documentations in docs are not referencing `static` folder in a unified way, that's why I need to copy `static` folder to both `versioned_docs` and `version-next` at the same time.

**Comment by FeynmanZhou** [comment]
@qweeah After moving the static folder, the icons svg seems not available on the preview link: https://deploy-preview-338--oras-project.netlify.app/docs/1.2/
image

**Comment by TerryHowe** [comment]
Since we don't build an artifact for each commit on main, I was wondering if we should have a next at all. The more copies, the more changes we are going to lose between releases.

Can we just create the next release off the latest when we get a release candidate?

**Comment by qweeah** [comment]
> @qweeah After moving the static folder, the icons svg seems not available on the preview link: https://deploy-preview-338--oras-project.netlify.app/docs/1.2/ image

@FeynmanZhou  It's true, the icons are missing but I checked other PR's preview deployment (e.g. https://deploy-preview-340--oras-project.netlify.app/)  and all those icons are missing. I think it's a bug in the netlify preview environment.

**Comment by qweeah** [comment]
> Can we just create the next release off the latest when we get a release candidate?

The jumbled reference comes from community folder, which should not belong to any release but it's currently put into the next release docs.

**Comment by qweeah** [comment]
closing as #344 is a better option.

**Pull request closed without merging**
