### PR TITLE
docs: update rust client

### PR DESCRIPTION
**Pull request by sajayantony**
-  @thomastaylor312 I'm just updateing the placeholders here. We can enhance the docs going forward. 

Preview - https://deploy-preview-355--oras-project.netlify.app/docs/client_libraries/rust

### CODE REVIEW

**Review by FeynmanZhou — DISMISSED** [review]
LGTM. Welcome a new client library

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
Ah, this file needs to be moved to the versioned_docs directories

**Comment by sajayantony** [comment]
PTAL @TerryHowe

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Pull request merged**
