### PR TITLE
Updating README.md file

### PR DESCRIPTION
**Pull request by RickDeb2004**
closes: #130

By using jq and pv, one can show the content downloading progress when using ORAS. This demonstrates how to fetch a blob with a specific reference, determine its size using jq, and use pv to display the progress while redirecting the output to a file named layer.bin.

### CODE REVIEW

**Comment by TerryHowe** [comment]
My understanding of that issue was that blurb would be added to the docs, not the readme

**Comment by RickDeb2004** [comment]
> My understanding of that issue was that blurb would be added to the docs, not the readme

should I add that in the docs>CLI>installation.mdx

**Comment by TerryHowe** [comment]
Either on https://oras.land/docs/CLI_Reference/oras_blob_fetch or on `oras pull` and `oras copy` if that was possible/meaningful.

**Comment by RickDeb2004** [comment]
> Either on https://oras.land/docs/CLI_Reference/oras_blob_fetch or on `oras pull` and `oras copy` if that was possible/meaningful.

ok sir

**Comment by RickDeb2004** [comment]
> Either on https://oras.land/docs/CLI_Reference/oras_blob_fetch or on `oras pull` and `oras copy` if that was possible/meaningful.

sir pls review #180

**Comment by TerryHowe** [comment]
Sounds like we are going a different direction here #180

**Pull request closed without merging**
