### PR TITLE
doc: Nominate Feynman Zhou to be a subproject owner

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Hi @oras-project/oras-www-maintainers @oras-project/oras-client-release-managers ,

I was actively contributing to this repo in the past 6 months. I raised [11 Pull Requests](https://github.com/oras-project/oras-www/pulls?q=is%3Apr+author%3AFeynmanZhou+) and 9 were merged. Meanwhile, I also helped maintainers review PRs in this repo. According to the [ORAS governance guide](https://github.com/oras-project/community/blob/main/governance/GOVERNANCE.md#subproject-owners), I think I am qualified to become a subproject owner for the ORAS-www project. 

So I nominate myself to be a subproject owner via this PR. With the permission of @oras-project/oras-www-maintainers , I can handle the PRs in ORAS-www in time. Please vote for my nomination proposal. Thanks!

### CODE REVIEW

**Review by SteveLasker — APPROVED** [review]
@FeynmanZhou , you’ve done a great job with prs and issues, including doc content. Almost more importantly, you’ve built up the ORAS community, expanding the awareness and contributions. 
It’s with great pleasure to approve this PR. 
LGTM

**Review by TerryHowe — APPROVED** [review]

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by vsoch — APPROVED** [review]

**Comment by sajayantony** [comment]
LGTM. 
Thanks for all the contributions @FeynmanZhou

**Review by sajayantony — APPROVED** [review]

**Comment by SteveLasker** [comment]
Congrats, @FeynmanZhou

**Comment by FeynmanZhou** [comment]
Thank you! @sajayantony @SteveLasker @TerryHowe @vsoch @shizhMSFT

**Pull request merged**
