### PR TITLE
feat: Add refreshed logo

### PR DESCRIPTION
**Pull request by TerryHowe**
With the logo updates from @vsoch it looks much better:

Screen Shot 2023-03-17 at 06 58 18

Looks somewhat better in light mode.

Closes: https://github.com/oras-project/oras-www/issues/15

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
cc @bridgetkromhout for review

**Comment by SteveLasker** [comment]
Silly question, is there a reason we don't make the O and R centers as transparent?

**Comment by vsoch** [comment]
+1 - I don't think the new logo is an improvement over the old one with the lack of transparency, and what appears to be a faint white border around the entire thing.

**Comment by SteveLasker** [comment]
does anyone have good svg tools and experience? 
I’ve hacked a few, but I wouldn’t call myself an expert in svg editing.

**Comment by vsoch** [comment]
I'm not, but I can delete the white centers!
oras-no-white-centers

or all the centers (light purple of the "A"

oras-no-centers

**Comment by vsoch** [comment]
Just curious, how exactly is this logo "refreshed?"

**Comment by TerryHowe** [comment]
> Just curious, how exactly is this logo "refreshed?"

https://github.com/oras-project/oras-www/issues/15

**Comment by TerryHowe** [comment]
Updated with image from @vsoch I'll have to get some new screen caps out

**Comment by shizhMSFT** [comment]
@TerryHowe Given the new website, is this PR still valid?

**Comment by TerryHowe** [comment]
> @TerryHowe Given the new website, is this PR still valid?

No, closing

**Pull request closed without merging**
